services:
  html-css-app:
    build:
      context: ./html-css
      dockerfile: Dockerfile
    ports:
      - "5172:80"
    container_name: poc-html-css
    restart: unless-stopped

  react-app:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
  nuxtjs-app:
    build:
      context: ./nuxtjs
      dockerfile: Dockerfile
    ports:
      - "5176:5176"
    environment:
      - NODE_ENV=production