name: push-to-mirror

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          persist-credentials: false

      - name: Add mirror remote & Push
        env:
          MIRROR_REPO: ${{ secrets.MIRROR_REPO_URL }}
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          if [ -z "${MIRROR_REPO_URL}" ]; then
            echo "ERROR: secrets.MIRROR_REPO_URL is not set"
            exit 1
          fi
          if [ -z "${MIRROR_TOKEN}" ]; then
            echo "ERROR: secrets.MIRROR_TOKEN is not set"
            exit 1
          fi
          AUTH_URL="https://x-access-token:${MIRROR_TOKEN}@github.com/${MIRROR_REPO}.git"
          git remote add mirror "$AUTH_URL"
          git push --prune mirror 'refs/heads/*:refs/heads/*'
          git push --tags mirror